#!/bin/bash

# kitchen_scene1_open_bottom_drawer
# kitchen_scene1_open_drawer_put_bowl
# kitchen_scene1_open_top_drawer
# kitchen_scene1_put_the_black_bowl_on_the_plate
# kitchen_scene1_put_the_black_bowl_on_top_of_the_cabinet
# kitchen_scene2_open_the_top_drawer_of_the_cabinet
# kitchen_scene2_put_the_black_bowl_at_the_back_on_the_plate
# kitchen_scene2_put_the_black_bowl_at_the_front_on_the_plate
# kitchen_scene2_put_the_black_bowl_in_the_middle_on_the_plate
# kitchen_scene2_put_the_middle_black_bowl_on_top_of_the_cabinet
# kitchen_scene2_stack_the_black_bowl_at_the_front_on_the_black_bowl_in_the_middle
# kitchen_scene2_stack_the_middle_black_bowl_on_the_back_black_bowl
# kitchen_scene3_put_the_frying_pan_on_the_stove
# kitchen_scene3_put_the_moka_pot_on_the_stove
# kitchen_scene3_turn_on_the_stove
# kitchen_scene3_turn_on_the_stove_and_put_the_frying_pan_on_it
# kitchen_scene4_close_the_bottom_drawer_of_the_cabinet_and_open_the_top_drawer
# kitchen_scene4_close_the_bottom_drawer_of_the_cabinet
# kitchen_scene4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet
# kitchen_scene4_put_the_black_bowl_on_top_of_the_cabinet
# kitchen_scene4_put_the_wine_bottle_in_the_bottom_drawer_of_the_cabinet
# kitchen_scene4_put_the_wine_bottle_on_the_wine_rack

# kitchen_scene5_close_the_top_drawer_of_the_cabinet
# kitchen_scene5_put_the_black_bowl_in_the_top_drawer_of_the_cabinet
# kitchen_scene5_put_the_black_bowl_on_the_plate
# kitchen_scene5_put_the_black_bowl_on_top_of_the_cabinet
# kitchen_scene5_put_the_ketchup_in_the_top_drawer_of_the_cabinet

# kitchen_scene6_close_the_microwave
# kitchen_scene6_put_the_yellow_and_white_mug_to_the_front_of_the_white_mug

# kitchen_scene7_open_the_microwave
# kitchen_scene7_put_the_white_bowl_on_the_plate
# kitchen_scene7_put_the_white_bowl_to_the_right_of_the_plate

# kitchen_scene8_put_the_right_moka_pot_on_the_stove
# kitchen_scene8_turn_off_the_stove

# kitchen_scene9_put_the_frying_pan_on_the_cabinet_shelf
# kitchen_scene9_put_the_frying_pan_on_top_of_the_cabinet
# kitchen_scene9_put_the_frying_pan_under_the_cabinet_shelf
# kitchen_scene9_put_the_white_bowl_on_top_of_the_cabinet
# kitchen_scene9_turn_on_the_stove_and_put_the_frying_pan_on_it
# kitchen_scene9_turn_on_the_stove

# kitchen_scene10_close_the_top_drawer_of_the_cabinet_and_put_the_black_bowl_on_top_of_it
# kitchen_scene10_close_the_top_drawer_of_the_cabinet
# kitchen_scene10_put_the_black_bowl_in_the_top_drawer_of_the_cabinet
# kitchen_scene10_put_the_butter_at_the_back_in_the_top_drawer_of_the_cabinet_and_close_it
# kitchen_scene10_put_the_butter_at_the_front_in_the_top_drawer_of_the_cabinet_and_close_it
# kitchen_scene10_put_the_chocolate_pudding_in_the_top_drawer_of_the_cabinet_and_close_it

# living_room_scene1_pick_up_the_alphabet_soup_and_put_it_in_the_basket
# living_room_scene1_pick_up_the_cream_cheese_box_and_put_it_in_the_basket
# living_room_scene1_pick_up_the_ketchup_and_put_it_in_the_basket
# living_room_scene1_pick_up_the_tomato_sauce_and_put_it_in_the_basket

# living_room_scene2_pick_up_the_alphabet_soup_and_put_it_in_the_basket
# living_room_scene2_pick_up_the_butter_and_put_it_in_the_basket
# living_room_scene2_pick_up_the_milk_and_put_it_in_the_basket
# living_room_scene2_pick_up_the_orange_juice_and_put_it_in_the_basket
# living_room_scene2_pick_up_the_tomato_sauce_and_put_it_in_the_basket

# living_room_scene3_pick_up_the_alphabet_soup_and_put_it_in_the_tray 169
# living_room_scene3_pick_up_the_butter_and_put_it_in_the_tray 131
# living_room_scene3_pick_up_the_cream_cheese_and_put_it_in_the_tray 214
# living_room_scene3_pick_up_the_ketchup_and_put_it_in_the_tray 238
# living_room_scene3_pick_up_the_tomato_sauce_and_put_it_in_the_tray 177

# living_room_scene4_pick_up_the_black_bowl_on_the_left_and_put_it_in_the_tray
# living_room_scene4_pick_up_the_chocolate_pudding_and_put_it_in_the_tray
# living_room_scene4_pick_up_the_salad_dressing_and_put_it_in_the_tray
# living_room_scene4_stack_the_left_bowl_on_the_right_bowl_and_place_them_in_the_tray
# living_room_scene4_stack_the_right_bowl_on_the_left_bowl_and_place_them_in_the_tray

# mujoco isaacsim
for task in living_room_scene4_stack_the_right_bowl_on_the_left_bowl_and_place_them_in_the_tray; do
    python scripts/advanced/collect_demo.py --sim=mujoco --task=libero_90.$task --num_envs=1 --max_demo_idx=10 # --render.mode pathtracing  --cust_name new_render_256_pathtracing_0
done
